"""Scans a Synty pack's demo maps for multi-part prop assemblies and records how the
pack's own artists put them together: for every mesh SM_X that has sibling meshes
named SM_X_<Part> placed near it, the parts' transforms in SM_X's local frame.

Run inside the editor (it switches levels and comes back):
    python Tools/ue_remote.py --file Tools/demo_assemblies.py
Edit PACK / MAPS below for another pack. Output: Docs/<Pack>_DemoAssemblies.md and .json.
The current level is saved first, then reloaded at the end.
"""
import unreal, json, math, os
# One entry per pack, so a pack's map list is recorded rather than overwritten each time somebody
# points this at a different one. Set PACK to whichever is being scanned.
PACKS = {
    'PolygonCyberCity': ['/Game/PolygonCyberCity/Maps/Demo_Interior',
                         '/Game/PolygonCyberCity/Maps/Demo',
                         '/Game/PolygonCyberCity/Maps/Overview'],
    'PolygonSciFiWorlds': ['/Game/PolygonSciFiWorlds/Maps/Demo_Explorer',
                           '/Game/PolygonSciFiWorlds/Maps/Demo_Corporation',
                           '/Game/PolygonSciFiWorlds/Maps/Demo_Scavenger',
                           '/Game/PolygonSciFiWorlds/Maps/Demo_BlackMarket',
                           '/Game/PolygonSciFiWorlds/Maps/Overview'],
    'PolygonSciFiSpace': ['/Game/PolygonSciFiSpace/Maps/Demonstration_Interior',
                          '/Game/PolygonSciFiSpace/Maps/Demonstration_Exterior',
                          '/Game/PolygonSciFiSpace/Maps/Overview'],
}
PACK = 'PolygonSciFiWorlds'
MAPS = PACKS[PACK]
OUT = r'C:\Dev\Games\RepliCan\Docs'
RADIUS = 400.0   # a part further than this from its root is another assembly's

les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
ues = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem)
ML = unreal.MathLibrary
home = ues.get_editor_world().get_path_name().split(':')[0].rsplit('.', 1)[0]
les.save_current_level()

def r1(v): return round(v, 1)
def fmt_rot(r): return (r1(r.roll), r1(r.pitch), r1(r.yaw))

assemblies = {}   # root mesh -> list of instances, each {map, root_loc, root_rot, parts: [(mesh, rel_loc, rel_rot, scale)]}
placements = {}   # mesh -> [z of pivot] for a sense of mounting heights
for mp in MAPS:
    if not les.load_level(mp): print('could not load', mp); continue
    comps = []
    for a in eas.get_all_level_actors():
        for c in a.get_components_by_class(unreal.StaticMeshComponent):
            m = c.static_mesh
            if not m: continue
            comps.append((m.get_name(), c.get_world_location(), c.get_component_rotation() if hasattr(c, 'get_component_rotation') else c.get_world_rotation(), c.get_world_scale() if hasattr(c, 'get_world_scale') else c.get_component_scale(), a.get_actor_label()))
    names = set(n for n, _, _, _, _ in comps)
    for n, loc, _, _, _ in comps: placements.setdefault(n, []).append(r1(loc.z))
    roots = sorted(n for n in names if any(o.startswith(n + '_') for o in names))
    print(mp, 'components', len(comps), 'assembly roots', roots)
    for root in roots:
        part_names = [o for o in names if o.startswith(root + '_')]
        root_insts = [c for c in comps if c[0] == root]
        part_insts = [c for c in comps if c[0] in part_names]
        for rn, rloc, rrot, rscale, rlabel in root_insts:
            T = unreal.Transform(rloc, rrot, unreal.Vector(1, 1, 1))
            parts = []
            for pn, ploc, prot, pscale, plabel in part_insts:
                if (ploc - rloc).length() > RADIUS: continue
                rel = ML.inverse_transform_location(T, ploc)
                rrel = ML.inverse_transform_rotation(T, prot)
                parts.append({'mesh': pn, 'loc': (r1(rel.x), r1(rel.y), r1(rel.z)), 'rot': fmt_rot(rrel), 'scale': (r1(pscale.x), r1(pscale.y), r1(pscale.z))})
            if parts:
                parts.sort(key=lambda p: (p['mesh'], p['loc']))
                assemblies.setdefault(root, []).append({'map': mp.rsplit('/', 1)[1], 'actor': rlabel, 'root_z': r1(rloc.z), 'root_rot': fmt_rot(rrot), 'root_scale': (r1(rscale.x), r1(rscale.y), r1(rscale.z)), 'parts': parts})
print('back home', les.load_level(home))

os.makedirs(OUT, exist_ok=True)
with open(os.path.join(OUT, PACK + '_DemoAssemblies.json'), 'w', encoding='utf-8') as f: json.dump(assemblies, f, indent=1)
lines = ['# %s: prop assemblies as placed in the pack\'s demo maps' % PACK, '',
         'Generated by Tools/demo_assemblies.py from %s.' % ', '.join(m.rsplit('/', 1)[1] for m in MAPS),
         'Each part is given in the ROOT mesh\'s local frame (location cm, rotation roll/pitch/yaw, scale).',
         'Where the pack places the same assembly several times, the first instance is spelled out and the',
         'others are summarised by how their parts differ (usually only the freely-aimed bit).', '']
for root in sorted(assemblies):
    insts = assemblies[root]
    lines.append('## %s  (%d placed)' % (root, len(insts)))
    first = insts[0]
    lines.append('First instance: %s in %s, pivot z %.1f, rot %s, scale %s' % (first['actor'], first['map'], first['root_z'], str(first['root_rot']), str(first['root_scale'])))
    lines.append('')
    lines.append('| part | local loc | local rot (roll, pitch, yaw) | scale |')
    lines.append('|---|---|---|---|')
    for p in first['parts']:
        lines.append('| %s | %s | %s | %s |' % (p['mesh'], str(p['loc']), str(p['rot']), str(p['scale'])))
    if len(insts) > 1:
        # per part mesh: the range of local locations and rotations across all instances
        by_mesh = {}
        for inst in insts:
            for p in inst['parts']: by_mesh.setdefault(p['mesh'], []).append(p)
        lines.append('')
        lines.append('Across all instances:')
        for mesh in sorted(by_mesh):
            ps = by_mesh[mesh]
            locs = set(p['loc'] for p in ps); rots = set(p['rot'] for p in ps)
            loc_s = ('fixed loc %s' % (next(iter(locs)),)) if len(locs) == 1 else ('loc varies over %d values, e.g. %s' % (len(locs), ', '.join(str(l) for l in list(locs)[:3])))
            rot_s = ('fixed rot %s' % (next(iter(rots)),)) if len(rots) == 1 else ('rot varies over %d values, e.g. %s' % (len(rots), ', '.join(str(r) for r in list(rots)[:3])))
            lines.append('- %s: %d placed; %s; %s' % (mesh, len(ps), loc_s, rot_s))
    lines.append('')
lines.append('## Pivot heights of every mesh placed (z of the component pivot, cm; demo floors are not all at z 0)')
lines.append('')
for n in sorted(placements):
    zs = placements[n]
    lines.append('- %s: %d placed, z %s..%s' % (n, len(zs), min(zs), max(zs)))
with open(os.path.join(OUT, PACK + '_DemoAssemblies.md'), 'w', encoding='utf-8') as f: f.write('\n'.join(lines) + '\n')
print('assemblies found:', sorted(assemblies), 'written to', OUT)
